import './globals.css'
import { Inter } from 'next/font/google'
import { LandingLayout } from '@components/common/organisms/LandingLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LandingLayout>{children}</LandingLayout>
      </body>
    </html>
  )
}
